# Generated by Django 4.0 on 2021-12-25 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mobile_details',
            new_name='Product_details',
        ),
    ]
